# Syncytium Mesh Model (SMM) Parameters
# All parameters with physical units documented
# Contact: Andreu.Ballus@uab.cat

# === Mesh Grid ===
# Spatial domain configuration
L_mm: 32.0              # Domain size (mm) - square domain Lx = Ly
dx_mm: 0.5              # Grid spacing (mm) - determines Nx = Ny = L/dx
Nx: 64                  # Number of grid points in x (computed as L/dx if not specified)
Ny: 64                  # Number of grid points in y

# === Glial Micro-Model Parameters ===
# IP₃/Ca reaction-diffusion system at microscale (linearized around steady state)
# ∂ₜc = -α·c + β·i  (Ca²⁺ fluctuation)
# ∂ₜi = γ·c - δ·i + D·Δi  (IP₃ fluctuation)
# These determine the mesoscopic telegraph equation parameters
alpha: 1.5              # Ca²⁺ decay rate (1/s) - SERCA uptake, buffering
beta: 0.8               # IP₃ → Ca²⁺ coupling (1/s) - IP₃R open probability
gamma: 1.0              # Ca²⁺ → IP₃ production (1/s) - PLC activation
delta: 1.0              # IP₃ degradation rate (1/s) - IP₃ phosphatase
D_um2_per_s: 100.0      # IP₃ diffusion coefficient (μm²/s) - gap junction coupling

# === Telegraph Equation Parameters (Derived) ===
# These are computed from micro-parameters. If specified here, they override the derivation.
# ∂²ψ/∂t² + 2γ₀·∂ψ/∂t + ω₀²·ψ - c_eff²·Δψ = S(r,t) + ξ(r,t)
# gamma0 = (alpha + delta) / 2
# c_eff² = D * (delta - alpha) / 2
# omega0² determined by local eigenvalues of (alpha, beta, gamma, delta)
# Leave these commented to use auto-computation from micro-parameters:
# gamma0: 1.25          # Damping coefficient (1/s) - auto: (α+δ)/2
# omega0: 0.0           # Oscillation frequency (rad/s) - auto: from eigenvalues
# c_eff_mm_per_s: 7.07  # Effective wave speed (mm/s) - auto: sqrt(D·(δ-α)/2)

# === Legacy PDE Parameters (for backward compatibility) ===
# These can be used if glial micro-model is disabled
c_mm_per_s: 15.0        # Wave speed (mm/s) - used if c_eff not derived
gamma_s: 0.5            # Background damping coefficient (1/s) - used if gamma0 not derived
dt_s: 0.001             # Time step (s) - must satisfy CFL condition
noise_sigma_mesh: 0.000001  # Mesh white noise amplitude

# === PML Boundaries ===
# Perfectly Matched Layer for absorbing boundaries
pml_width_mm: 3.0       # Width of PML region (mm)
pml_sigma_max: 50.0     # Maximum PML damping coefficient (1/s)

# === Neural Mass Parameters ===
# Wilson-Cowan-like dynamics per region
N_regions: 16           # Number of neural regions
tau_E_s: 0.01           # Excitatory time constant (s)
tau_I_s: 0.01           # Inhibitory time constant (s)
w_EE: 1.5               # E→E synaptic weight
w_EI: 1.2               # I→E synaptic weight
w_IE: 1.0               # E→I synaptic weight
w_II: 0.5               # I→I synaptic weight
sigmoid_gain: 4.0       # Sigmoid activation gain
sigmoid_threshold: 0.5  # Sigmoid activation threshold

# === Kuramoto Parameters ===
# Phase oscillators on structural connectome
K_kuramoto: 0.5         # Kuramoto coupling strength
omega_mean_hz: 4.0      # Mean natural frequency (Hz)
omega_std_hz: 0.5       # Std dev of natural frequencies (Hz)

# === Tripartite Coupling Parameters ===
# Inter-layer coupling strengths for neurons ⇄ glia ⇄ connectivity

# (a) Neurons → Glia (source term)
coupling_E_to_glia: 0.0       # Excitatory → glia source strength (β_E)
coupling_I_to_glia: 0.0       # Inhibitory → glia source strength (β_I)
coupling_theta_to_glia: 0.0   # Kuramoto phase → glia source strength (β_θ)
sigma_kernel_mm: 1.0          # Gaussian source kernel width (mm) - astrocyte domain size

# (b) Glia → Neurons (gliotransmission)
coupling_glia_to_neural: 0.0  # Glia → neural excitability (g_A)
glia_nonlinearity: 'linear'   # Options: 'linear', 'tanh', 'sigmoid', 'threshold_linear'
glia_threshold: 0.0           # Threshold for threshold_linear nonlinearity
glia_gain: 1.0                # Gain for sigmoid/tanh nonlinearity

# (c) Glia → Kuramoto (phase modulation)
coupling_glia_to_kuramoto: 0.0   # Glia → phase dynamics (κ_ψ)

# (d) Glia → Connectivity (Ca-gated plasticity)
enable_plasticity: false      # Enable slow connectivity plasticity
tau_C_s: 60.0                 # Connectivity time constant (s)
lambda_C: 0.1                 # Connectivity decay rate (1/s)
eta_H: 0.01                   # Hebbian learning rate
eta_psi: 0.01                 # Glial plasticity rate
sigma_psi_target: 0.1         # Target glial covariance for homeostasis

# Legacy coupling (for backward compatibility)
coupling_neural_mesh: 0.0     # E→mesh source strength (replaced by coupling_E_to_glia)
coupling_mesh_kuramoto: 0.0   # mesh→Kuramoto modulation (replaced by coupling_glia_to_kuramoto)
coupling_mesh_neural: 0.0     # mesh→neural feedback (replaced by coupling_glia_to_neural)

# === Simulation Parameters ===
sim_duration_s: 10.0    # Total simulation time (s)
seed: 42                # Random seed for reproducibility

# === Ensemble Parameters ===
# For ensemble PSD computation
ensemble_size: 50       # Number of ensemble members

# === Analysis Parameters ===
# PSD computation settings
psd_fs: 250             # Sampling rate for PSD analysis (Hz)
psd_nperseg: 512        # Welch's method segment length
psd_noverlap: 256       # Welch's method overlap

# Phase gradient coherence settings
pgc_band_low: 1.0       # Low frequency for bandpass (Hz)
pgc_band_high: 8.0      # High frequency for bandpass (Hz)
pgc_window_s: 0.5       # Window duration (s)
pgc_step_s: 0.25        # Step size for sliding window (s)
